import { COLOR } from "@/theme/theme";

export const styles = {
  container: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 14,
  },
  recipientCard: {
    padding: "10px 14px",
    background: COLOR.BACKGROUND.SUBTLE,
    borderRadius: 8,
    border: `1px solid ${COLOR.BORDER.SUBTLE}`,
    display: "flex",
    flexDirection: "column" as const,
    gap: 8,
  },
  recipientHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  recipientTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: COLOR.TEXT.PRIMARY,
  },
  phoneInputRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  phoneLabel: {
    fontSize: 12,
    color: COLOR.TEXT.SECONDARY,
    flexShrink: 0,
  },
  phoneInput: {
    flex: 1,
    padding: "6px 10px",
    fontSize: 13,
    borderRadius: 6,
    border: `1px solid ${COLOR.BORDER.DEFAULT}`,
    background: COLOR.INPUT.PRIMARY.BACKGROUND,
    color: COLOR.TEXT.PRIMARY,
    outline: "none",
  },
  checkboxCard: {
    padding: "12px 14px",
    background: COLOR.BACKGROUND.SUBTLE,
    borderRadius: 8,
    border: `1px solid ${COLOR.BORDER.SUBTLE}`,
    display: "flex",
    flexDirection: "column" as const,
    gap: 12,
  },
  checkboxCardHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  checkboxCardTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: COLOR.TEXT.PRIMARY,
  },
  checkboxGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(230px, 1fr))",
    gap: "10px 16px",
  },
  previewContainer: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 6,
  },
  previewHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  previewTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  previewLabel: {
    fontSize: 13,
    fontWeight: 600,
    color: COLOR.TEXT.PRIMARY,
  },
  editedBadge: {
    fontSize: 11,
    padding: "2px 6px",
    borderRadius: 4,
    background: "#fef3c7",
    color: "#b45309",
    fontWeight: 500,
  },
  previewActions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  actionButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    fontSize: 12,
    fontWeight: 500,
    padding: "4px 8px",
    borderRadius: 6,
    border: `1px solid ${COLOR.BORDER.DEFAULT}`,
    background: COLOR.BACKGROUND.SECONDARY,
    color: COLOR.TEXT.PRIMARY,
    cursor: "pointer",
    transition: "background 150ms ease",
  },
  copiedButton: {
    borderColor: "#16a34a",
    color: "#16a34a",
  },
  textarea: {
    width: "100%",
    padding: "10px 12px",
    borderRadius: 8,
    border: `1px solid ${COLOR.BORDER.DEFAULT}`,
    background: COLOR.BACKGROUND.PRIMARY,
    color: COLOR.TEXT.PRIMARY,
    fontSize: 13,
    lineHeight: 1.5,
    resize: "vertical" as const,
    fontFamily: "inherit",
    outline: "none",
    boxSizing: "border-box" as const,
  },
  textareaHint: {
    fontSize: 11,
    color: COLOR.TEXT.SECONDARY,
    margin: 0,
  },
};
